//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventVoting.VotingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appliance
    {
        public long Id { get; set; }
        public int Type { get; set; }
        public byte[] DeviceId { get; set; }
    }
}
