//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using System;
using System.Data.SQLite;
using System.Data.SQLite.EF6;



namespace VotingApp
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Appliance>();
                db.CreateTable<Vote>();
                db.CreateTable<Voting>();
            }
        }
    }
    public partial class Appliance
    {
        [PrimaryKey]
        public Int64 Id { get; set; }
        
        [NotNull]
        public Int32 Type { get; set; }
        
        [NotNull]
        public Byte[] DeviceId { get; set; }
        
    }
    
    public partial class Vote
    {
        [PrimaryKey]
        public Int64 Id { get; set; }
        
        [NotNull]
        public Int64 IdVoting { get; set; }
        
        [NotNull]
        public Int64 IdAppliance { get; set; }
        
        public Int32? Result { get; set; }
        
    }
    
    public partial class Voting
    {
        [PrimaryKey]
        public Int64 Id { get; set; }
        
        [MaxLength(100)]
        public String Name { get; set; }
        
        public DateTime? Start { get; set; }
        
        public DateTime? End { get; set; }
        
    }
    
}
