//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventVoting.VotingApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VotingDbContext : DbContext
    {
        public VotingDbContext()
            : base("name=VotingDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vote> Vote { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Voting> Voting { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<EventDevice> EventDevice { get; set; }
    }
}
