//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventVoting.VotingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public long Id { get; private set; }
        public long IdVoting { get; set; }
        public long IdAppliance { get; set; }
        public Nullable<int> Result { get; set; }
    }
}
