BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Event` (
	`Id`	INTEGER NOT NULL UNIQUE,
	`Name`	TEXT,
	PRIMARY KEY(`Id`)
);
CREATE TABLE IF NOT EXISTS `Appliance` (
	`Id`	INTEGER NOT NULL UNIQUE,
	`Type`	INT NOT NULL,
	`DeviceId`	BINARY ( 16 ) NOT NULL,
	PRIMARY KEY(`Id`)
);
CREATE TABLE IF NOT EXISTS `Voting` (
	`Id`	INTEGER NOT NULL UNIQUE,
	`IdEvent`	BIGINT NOT NULL,
	`Start`	DATETIME,
	`End`	DATETIME,
	`Name`	TEXT,
	PRIMARY KEY(`Id`)
);
CREATE TABLE IF NOT EXISTS `Vote` (
	`Id`	INTEGER NOT NULL UNIQUE,
	`IdVoting`	BIGINT NOT NULL,
	`IdAppliance`	BIGINT NOT NULL,
	`Result`	INT,
	PRIMARY KEY(`Id`)
);
CREATE INDEX IF NOT EXISTS `IxVotingIdEvent` ON `Voting` (
	`IdEvent`	ASC
);
CREATE INDEX IF NOT EXISTS `IxVoteIdVoting` ON `Vote` (
	`IdVoting`	ASC
);
COMMIT;
