BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS Event (
	Id INTEGER PRIMARY KEY,
	Name	TEXT
);

CREATE TABLE IF NOT EXISTS Device (
	Id	INTEGER PRIMARY KEY,
	Type	INT NOT NULL,
	DeviceId	BINARY ( 16 ) NOT NULL
);

CREATE TABLE IF NOT EXISTS EventDevice (
	IdEvent	BIGINT NOT NULL,
	IdDevice BIGINT NOT NULL,
	PRIMARY KEY(IdEvent, IdDevice)
);

CREATE TABLE IF NOT EXISTS Voting (
	Id	INTEGER PRIMARY KEY,
	IdEvent	BIGINT NOT NULL,
	Start	DATETIME,
	End	DATETIME,
	Name	TEXT
);
CREATE TABLE IF NOT EXISTS Vote (
	Id	INTEGER PRIMARY KEY,
	IdVoting	BIGINT NOT NULL,
	IdAppliance	BIGINT NOT NULL,
	Result	INT
);
CREATE INDEX IF NOT EXISTS IxVotingIdEvent ON Voting (
	IdEvent	ASC
);
CREATE INDEX IF NOT EXISTS IxVoteIdVoting ON Vote (
	IdVoting ASC
);
COMMIT;
